// ^Eventos.
// ^Los eventos en React son mecanismos mediante los cuales nuestros componentes pueden reaccionar a cualquier interacción realizada por el usuario dentro de la aplicación. Estas interacciones pueden ser muy variadas, como hacer clic sobre un botón, escribir dentro de un input, mover el cursor del mouse, presionar una tecla del teclado, enviar un formulario, seleccionar un elemento, enfocar o desenfocar un campo, arrastrar elementos y, en general, prácticamente cualquier acción que el usuario pueda realizar dentro del navegador. React cuenta con una enorme cantidad de eventos ya implementados, los cuales siguen el estándar de los eventos del DOM, aunque internamente React los maneja mediante su propio sistema conocido como **SyntheticEvent**, el cual unifica el comportamiento de los eventos entre los diferentes navegadores para ofrecer un funcionamiento más consistente. Es posible consultar la lista completa de eventos disponibles dentro de la documentación oficial de React: https://es.legacy.reactjs.org/docs/events.html. Comúnmente, y en su gran mayoría, los nombres de los eventos comienzan con el prefijo **on**, encontrando ejemplos como `onClick`, `onChange`, `onSubmit`, `onMouseEnter`, `onMouseLeave`, `onKeyDown`, entre muchos otros. Es importante recordar que cuando trabajábamos con HTML, CSS y JavaScript puro, los eventos normalmente se declaraban directamente dentro de las etiquetas HTML mediante atributos como `onclick=""`, `onchange=""` u otros similares, los cuales llamaban funciones declaradas dentro de un archivo JavaScript externo. Esto era posible porque dichas funciones existían de manera global dentro del archivo JS. Sin embargo, en React el funcionamiento cambia ligeramente, ya que los eventos forman parte del propio componente y, por lo tanto, la lógica asociada a dichos eventos normalmente también se declara dentro del mismo componente. Esto hace que cada componente sea mucho más independiente, reutilizable y sencillo de mantener, ya que cada uno contiene tanto su estructura visual como la lógica necesaria para responder a las acciones del usuario. En resumen, los eventos en React siempre se declaran dentro de los componentes y son estos quienes administran las funciones que serán ejecutadas cuando ocurra determinada interacción del usuario.
// ~Declaración de eventos en React.
// ~La declaración de eventos dentro de React es bastante sencilla y muy similar a como se hacía anteriormente en HTML puro. La principal diferencia consiste en que, mientras que en HTML el valor del evento se escribía directamente como texto, en React el valor que se coloca después del signo igual (`=`) deberá ir siempre entre llaves `{}`. Esto se debe a que las llaves indican a JSX que el contenido deberá interpretarse como código JavaScript y no como texto plano. Gracias a ello podemos llamar funciones, ejecutar expresiones, utilizar variables o realizar prácticamente cualquier operación de JavaScript directamente desde nuestros eventos. Lo más común es asociar una función previamente declarada dentro del mismo componente para que esta sea ejecutada únicamente cuando el usuario dispare el evento correspondiente. Es importante mencionar nuevamente que dichas funciones normalmente deben encontrarse dentro del mismo componente donde se utiliza el evento, ya que forman parte de la lógica propia de ese componente. Adicionalmente, existe un detalle extremadamente importante que suele generar errores cuando se comienza a trabajar con React: **al asignar una función directamente a un evento NO deben colocarse paréntesis**. Esto sucede porque las llaves `{}` evalúan inmediatamente la expresión que contienen. Si escribimos `nombreFuncion()`, la función será ejecutada inmediatamente durante el renderizado del componente y **no** cuando ocurra el evento. En cambio, si únicamente escribimos `nombreFuncion`, React almacenará la referencia de la función y la ejecutará únicamente cuando el usuario realice la acción correspondiente (por ejemplo un clic). Únicamente en situaciones donde realmente necesitemos enviar parámetros o ejecutar lógica adicional será necesario utilizar funciones flecha dentro del evento. Por ello, la forma más común y recomendada consiste simplemente en pasar la referencia de la función sin paréntesis, ya que esto permite que React controle correctamente el momento exacto en el que dicha función deberá ejecutarse.
function NombreComponente() { //* Se declara un componente funcional de React.
    let sumar = () => { //* Se declara una función flecha que posteriormente será utilizada por algún evento del componente.
        //* Aquí se escribiría la lógica que deseamos ejecutar cuando el evento sea disparado.
    }; //* Finaliza la función sumar.

    return ( //* El componente retorna el contenido visual que será renderizado en el DOM.
        <> //* Fragment permite agrupar múltiples elementos sin agregar nodos adicionales al DOM.
            <button onClick={sumar}>Sumar</button> //* Se declara un botón que, al hacer clic sobre él, ejecutará la función sumar.
        </> //* Finaliza Fragment.
    ); //* Finaliza el return.
} //* Finaliza el componente.

export default NombreComponente; //* Se exporta el componente para poder utilizarlo desde otros archivos.