// ^Eventos
// ^Los eventos en React son mecanismos por los cuales los componentes pueden reaccionar a la interaccion del usuario, pudiendo ser mediante un click, escrituras es inputs, mover el mousey cualquier tipode interaccion que realice el usuario con el navegador. Por lo que existen una inmensa cantidad de eventos dentro de react pudiendo encontrar todos los tipos aqui "https://es.legacy.reactjs.org/docs/events.html". Cimunmnete y en su malloria los eventgos inician con "on", pudiendo encontrar erjemplos como onClic, onHover. etc.. Por lo que ademas es importante resatas y es que si bien recordamos cuando teniamos un archivo HTML que mediante script estaba vinculado a un archivo JS, la forma de declarar eventos dentro de las etiquetas html consistia en colocar el nombre del evento dentro de la etiqueta html y luego asignarle una funcion que se ejecutaria cuando el evento se disparara, quedando algo como lo siguiente: <button onclick="miFuncion()">Click me</button>, esto debido a que en HTML los eventos se declaraban de manera global, por lo que cualquier funcion declarada en el archivo JS podia ser llamada desde cualquier parte del archivo HTML. Por lo que en React la forma de declarar eventos es diferente, ya que los eventos se declaran dentro de los componentes y no de manera global, por lo que si queremos declarar un evento dentro de un componente debemos hacerlo dentro del mismo componente, y no fuera de este, ya que si lo hacemos fuera del componente el evento no funcionara. Por lo que la forma correcta de declarar un evento dentro de un componente es la siguiente: <button onClick={miFuncion}></button>, donde miFuncion es una funcion declarada dentro del mismo componente y no fuera de este. Por lo que es importante resaltar que los eventos en React son declarados dentro de los componentes y no de manera global, por lo que si queremos declarar un evento dentro de un componente debemos hacerlo dentro del mismo componente, y no fuera de este, ya que si lo hacemos fuera del componente el evento no funcionara.
// ~Declaracion de eventos en React.
// ~La declraracion de los eventos dentro de React es muy simple, ya que de igual manera en HTML puro ingresavamos el evento como por ejemplo "<button onClick=nombreFuncion()>Click me</button>", en React se mantiene casi de la misma manera, donde unicamente se cambiara lo que se dentrara e el simbolo igual dentro del evento esto ya que se deberen como se venia comentando anteriormente implementar llavbes (esto para ejecutar o llamar codigo JS de nuestro componente), y dentro de este podemos mandar llamar o directamente ejecutar codigo, el cual sera ejecutado en ambos caso siempre y cuando el evento se ejecute, quedando de la siguiente manera: "<button onClick={nombreFuncion()}>Click me</button>", donde nombreFuncion es una funcion declarada dentro del mismo componente y no fuera de este, pudiendo tambien llamar variables unicamente u otro tipo de elementos segun sea el caso. Por lo que es importante resaltar que los eventos en React son declarados dentro de los componentes y no de manera global, por lo que si queremos declarar un evento dentro de un componente debemos hacerlo dentro del mismo componente, y no fuera de este, ya que si lo hacemos fuera del componente el evento no funcionara.
function NombreComponente() {
    let sumar = () => {}
    return (
        <>
            <button onClick={sumar()}></button>
        </>
    );
}

export default NombreComponente;