// ^Hooks y Estados.
// ^Antes de la version 16.8 de React, se usaban los classBase component los cuales son los componentes de tipo clase anteriormente vistro en secciones previas, por lo que habia una gran diferencia en el manejo de estado, por que el estado habia que llamarlo con dist. para que hiciera referencia y de esa manera react saboia si debia cambiar o no. Por l,o que sin muchos explicacionems era bastente dsistinto y complejo donde actualmente dejado de lado. Pero todo esto cambio totalmente deste que react implemento los Hooks, los cuales esto se utilizan casi de manerra obligatoria flushecompontns y ademas se usan los hooks. Los cuales los Hooks son funciones especiales que nos permiten utilizar una funcion de React en un componente de tipo funcion, losa cuales fueron introducciones en la version 16.8 de react para poder manejar el estado y otras caracterusutucas de react sin la necesitad de utilizar componentes de tipo clase, Los hookc vienen de dos formas vienen los propios de reatc como useState useEfect useMemo,etc.. y tambien poodemos crear Hooks propios los cuales son los custome hooks, son una forma de hacer una funcion facil, legible y reutilizable. <Por lo que es realmen te fundamental entednder un concepto base y s que datos como eventois que activan o ejecutan ciertas cosas o las variables que almacewnan datos quizas se envian o se actualizan, pero estos quedan atrapados en memoria por lo que en React se divide en 2 partes lo que se almacena y trransforma en la parte de JavaScrip y lo que React muestra en pantalla, por lo que si quizas un dato se actulizo en memroa pero en pantalla se sigue mostrando el dato anterior por lo que para eso son los Hooks pirmitiendo rewpintar elementos, elementos en el front-end conectando la logica con la interfaz, por lo que en este punto entran los estados, donde como bien dijimos las variables en general sabemos que se pueden actulizar valores pero solo en memoria ya que si bien tenemos o queremos actualizar y repintar dicha variable para ser mostrada deberemos aplicarle um Hook el cual ante React se le declarara un estado a dicha variable, donde un estado en react es un objeto que contiene datos y representa la informacion que una interfaz de usuario necesita para poder renderizarse y funcionar de manera correcta, donde dichos estados son mutables y tiene todos los datos ue necesita un componente para funcionar de manera correcta y mutar si es lo que necesita por l oque atravez de hooks de los funcional componentes (componenters de tipo funcion) o los constructores en los class componentes (componentes de tipo clase) uno puede ir modificansdo este estadop y react de manera automatica e intentilengete solamente modificara la parte del componente ue a interactuado con el usuario.
// ~UseState.
// ~Como  bien se hizo mencion anteriormente los Hooks son funciones que nos permiten actualizar, modificar o interactuiar con lo que React pinta en nuestrs pagina web, por lo que en el caso del Hook useState, este nos permite agregarle un erstado a una variable cualquiera, la cual al momento de declarar esta variable en la parte HTML dentro de nuestro componente, React de manera automatica aplicara una especie de listener donde si se actualiza nuiestra variable en el apartado de memoria (JavaScript), de forma automatica tambien repintara en la pagina web la informacion actualizada. Ya que hay que recordar que las variables de forma automaticas pese a ingresarlas en el HTML y actualizar o cambiar sus valores estos no se actualizan en la pagina web, ya que React no sabe que dicha variable cambio, por lo que para eso es necesario aplicar un Hook de estado a dicha variable, donde el Hook useState nos permite crear un estado para una variable y ademas nos devuelve un arreglo con dos elementos, el primero es la variable en si y el segundo es una funcion que nos permite actualizar el valor de dicha variable, por lo que al momento de actualizar el valor de la variable React se dara cuenta y repintara la pagina web con la informacion actualizada. Ademas es indispensable importar el Hook useState desde la libreria de React para poder utilizarlo dentro de nuestro componente, ya que si no lo importamos React no sabra que es un Hook y nos dara un error. Por lo que a continuacion se muestra un ejemplo de como utilizar el Hook useState dentro de un componente funcional de React.
// ?Importacion de useState.
// ?Para poder importar un Hoock y en este caso useState solamente mediante import y llaves {} delcararemos que importaremos useSte desde react utilizando from 'Reac', esto debido a que estros son hoock porpios de React y no es necesario instalar otra libreria o cosas. Por lo que la implementacion completa quedaria como import { useState } from "react"; donde unicamente con esto podremos ya implementar nuestro Hook.
import { useState } from "react";


