// ^Build & Dist.
// ^Bien sabemos que para desplegar o ejecutar una página web dentro de un servidor en producción, o dentro del entorno final donde será accesible para los usuarios, primero deberemos generar un **build**, ya que dicho proceso se encarga de tomar nuestro código de desarrollo y transformarlo en una versión final que pueda ser procesada y ejecutada por el navegador o por el servidor que se encargará de servir nuestra aplicación. Por lo tanto, el servidor no ejecutará directamente toda la estructura con la que nosotros trabajamos durante el desarrollo, sino que utilizará los archivos resultantes de la compilación. En el caso de React, aunque durante el desarrollo trabajamos con componentes, archivos JSX, módulos, Hooks y muchas otras herramientas propias del ecosistema de React, al momento de generar una build todo esto será procesado y transformado a archivos que finalmente puedan ser interpretados por el navegador, principalmente **HTML, CSS y JavaScript**. Esto se debe a que un navegador no entiende directamente componentes de React ni la sintaxis JSX como nosotros la escribimos durante el desarrollo, por lo que herramientas como Vite se encargan de transformar y empaquetar todo nuestro código para generar una versión final compatible con el entorno de producción. Por lo tanto, la build generada contendrá absolutamente toda la lógica, estructura, estilos, componentes, imágenes, dependencias y demás recursos que utilizamos dentro de nuestra aplicación React, pero organizados y transformados a un formato final que pueda ser servido y ejecutado correctamente. Además, como bien vimos previamente, existe `StrictMode`, el cual durante el desarrollo puede provocar comportamientos que nos ayuden a detectar errores, como la ejecución adicional de determinadas funciones y efectos. Sin embargo, debemos recordar que `StrictMode` es una herramienta orientada al **desarrollo y detección de problemas**, por lo que este comportamiento adicional no representa el funcionamiento normal de la aplicación en producción. Por ello, cuando generemos nuestro build final, las comprobaciones adicionales de desarrollo asociadas a `StrictMode` no provocarán las mismas ejecuciones duplicadas que podemos observar mientras desarrollamos. En producción nuestra aplicación funcionará con el comportamiento normal correspondiente a los componentes y efectos.
// ~Comando para la generacion del build mediante React.
// ~Para poder generar un build dentro de un proyecto React es relativamente sencillo, ya que normalmente cuando creamos el proyecto mediante herramientas como Vite nuestro `package.json` ya contiene un script preparado específicamente para realizar esta tarea. Si mantenemos dicho comando sin modificar, podremos utilizar directamente `npm run build` desde nuestra consola para iniciar el proceso de compilación. Internamente, dicho script ejecutará la herramienta de construcción configurada en nuestro proyecto, que en este caso será Vite, y esta será la encargada de procesar todos nuestros archivos, transformar JSX y JavaScript, procesar los estilos, optimizar los recursos y finalmente generar los archivos necesarios para producción. Por el contrario, si nosotros modificamos el nombre del script de generación del build dentro de `package.json`, entonces deberemos ejecutar `npm run nombreVariableBuild`, sustituyendo dicho nombre por el nombre que nosotros hayamos asignado al script correspondiente. Por lo tanto, lo importante no es solamente recordar el comando, sino comprender que `npm run` ejecutará el script definido dentro de la sección `"scripts"` de nuestro `package.json`, y ese script será el encargado de iniciar todo el proceso de construcción de nuestra aplicación.
// *npm run build //* Ejecuta el script "build" definido dentro de package.json e inicia el proceso de compilación para producción.

// ~Archivos de build.
// ~Una vez que ejecutemos en nuestra consola el comando encargado de generar el build, Vite comenzará a procesar todo nuestro proyecto y, una vez finalizado correctamente el proceso, nos mostrará en la terminal información detallada sobre el resultado de la compilación. Dentro de esta información podremos observar datos relacionados con los archivos que fueron transformados, la cantidad de módulos procesados, el tamaño final de los archivos generados, el tamaño comprimido mediante gzip y, dependiendo de las herramientas o plugins utilizados dentro del proyecto, también podremos encontrar información adicional relacionada con los tiempos empleados durante el proceso de construcción. Por defecto, Vite genera nuestra build dentro de una carpeta llamada **`dist`**, que significa *distribution*, y es precisamente dentro de esta carpeta donde encontraremos los archivos finales que posteriormente podremos desplegar en un servidor. En otras palabras, la carpeta `dist` representa la versión compilada y preparada para producción de nuestra aplicación. Dentro de ella podremos encontrar normalmente un archivo `index.html`, archivos JavaScript, archivos CSS y una carpeta de recursos o `assets` donde Vite coloca diferentes archivos necesarios para que nuestra aplicación funcione correctamente. Es importante mencionar que Vite también puede aplicar procesos de optimización y utilizar nombres con hash para determinados archivos, como `index-CVqNvb3e.js`, lo cual ayuda principalmente a controlar el almacenamiento en caché del navegador y evitar problemas cuando se publica una nueva versión de la aplicación. Además, si durante la compilación existe algún error, Vite detendrá el proceso y nos mostrará información relacionada con dicho problema para que podamos corregirlo antes de realizar el despliegue. Por el contrario, si el proceso finaliza correctamente, veremos un mensaje indicando que el build fue generado con éxito. Por lo tanto, una vez terminado el proceso, podremos encontrar nuestra build dentro de la carpeta `dist`, y normalmente esta es precisamente la carpeta que se toma como resultado final para desplegar nuestra aplicación React en un servidor o plataforma de hosting.
//* PS D:\Trabajos\Cursos\React-Course\Course> npm run build  

//* > course@0.0.0 build
//* > vite build

//* vite v8.1.3 building client environment for production... //* Vite indica que comenzará a construir la aplicación utilizando la configuración del entorno de producción.
//* ✓ 17 modules transformed. //* Se informa que 17 módulos fueron procesados y transformados durante la compilación.
//* computing gzip size... //* Vite calcula también el tamaño aproximado de los archivos después de aplicar compresión gzip.
//* dist/index.html                  2.06 kB │ gzip:  0.98 kB //* Se muestra el archivo HTML principal generado dentro de la carpeta dist junto con su tamaño original y comprimido.
//* dist/assets/index-CVqNvb3e.js  192.89 kB │ gzip: 61.11 kB //* Se muestra el archivo JavaScript generado dentro de assets, incluyendo el hash en su nombre y sus tamaños original y comprimido.

//* [PLUGIN_TIMINGS] Your build spent significant time in plugins. Here is a breakdown: //* Vite informa que una parte importante del tiempo de compilación estuvo relacionada con determinados plugins.
//*   - @rolldown/plugin-babel (48%) //* Este plugin representó el 48% del tiempo reportado durante esta ejecución del build.
//*   - vite:build-html (47%) //* Este proceso relacionado con la generación del HTML representó el 47% del tiempo reportado.
//* See https://rolldown.rs/reference/InputOptions.checks#plugintimings for more details. //* Se proporciona documentación adicional para conocer con mayor detalle estos tiempos y su funcionamiento.

//* ✓ built in 4.12s //* Vite confirma que la construcción terminó correctamente y muestra el tiempo total empleado.
//* PS D:\Trabajos\Cursos\React-Course\Course> //* La consola vuelve a quedar disponible una vez finalizado correctamente el proceso.